version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-photographer
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: photographer_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1q2w3e4r
    ports:
      - "3306:3306"
    networks:
      - photographer-service-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6.2
    container_name: redis-cache-photographer
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - photographer-service-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  redis_data:

networks:
  photographer-service-network:
    driver: bridge